### PR TITLE
Upgrade LMAX Disruptor to version `4.0.0`

### PR DESCRIPTION
**Pull request by sullis**
https://github.com/LMAX-Exchange/disruptor/releases/tag/4.0.0

### CODE REVIEW

**Comment by vy** [comment]
@sullis, could you remove [this dependabot ignore rule](https://github.com/apache/logging-log4j-samples/blob/44c3348906d2d160e6affd152e63eaa0c0554d76/.github/dependabot.yaml#L49) too, please?

**Comment by sullis** [comment]
> @sullis, could you remove [this dependabot ignore rule](https://github.com/apache/logging-log4j-samples/blob/44c3348906d2d160e6affd152e63eaa0c0554d76/.github/dependabot.yaml#L49) too, please?

Done.

**Comment by vy** [comment]
@sullis, you need to sign your commits too:

```
git reset HEAD~2
git commit -a -S -m 'Upgrade LMAX Disruptor to version 4.0.0 (#136)'
git push -f origin
```

**Comment by sullis** [comment]
Force pushed my latest update.

**Comment by vy** [comment]
@sullis, I think you used `-s` instead of `-S` I shared. I cannot see commit signatures, but a sign-off comment.

(Sorry for the trouble. As you know, I could have implemented this change and pushed it to `main` myself in 30 seconds. I am just trying to help you get the credits and introduce you to the right way of contributing to Log4j.)

**Comment by sullis** [comment]
I just pushed another update.

**Pull request merged**
